In [5]:
import numpy as np 

In [8]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
Z = np.zeros(10)
Z[5] = 5
print(Z)

[0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]


In [13]:
Z= np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [16]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [17]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [20]:
nz = np.nonzero([1,2,0,0,0,4,0])
print(nz)

(array([0, 1, 5]),)


In [21]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.87107873 0.10356734 0.84362642]
  [0.93444939 0.98370559 0.90703795]
  [0.07549798 0.36861867 0.18994164]]

 [[0.9880498  0.70535844 0.83835451]
  [0.39258706 0.56197214 0.00861844]
  [0.43246083 0.71713762 0.94351843]]

 [[0.73031757 0.84828023 0.55504227]
  [0.04705901 0.16260344 0.29614632]
  [0.59131775 0.8585585  0.70647049]]]


In [24]:
Z = np.random.random((10,10))
print(Z)
Zmin, Zmax = Z.min(),Z.max()
print(Zmin,Zmax)

[[0.77146676 0.10539498 0.06827272 0.29435041 0.11688455 0.06901774
  0.61214467 0.50618191 0.06131029 0.12450126]
 [0.1925625  0.72664282 0.18167315 0.39794366 0.30381996 0.91295802
  0.40531859 0.61629524 0.05542672 0.84155119]
 [0.85775564 0.97780728 0.58667015 0.97436419 0.11660168 0.36721155
  0.67555641 0.72696848 0.66909645 0.38027488]
 [0.26521786 0.8652207  0.87804217 0.78209018 0.42227343 0.5209676
  0.67428098 0.08864652 0.76860839 0.59566945]
 [0.80363468 0.45990003 0.57901019 0.73753297 0.19541796 0.45997378
  0.5196826  0.88448333 0.03902805 0.93450883]
 [0.90762673 0.51053853 0.81562363 0.59505394 0.20126972 0.28040974
  0.02467165 0.23281911 0.4646508  0.70316463]
 [0.2364311  0.29754686 0.99366323 0.83817057 0.96795887 0.20585673
  0.91850522 0.68280549 0.36681471 0.34452177]
 [0.82940915 0.73324838 0.32140425 0.53490102 0.06732635 0.40874464
  0.63259216 0.1829795  0.9365959  0.92377587]
 [0.5897548  0.62671515 0.69897722 0.64419155 0.50351002 0.6923363
  0.8746573  0

In [26]:
Z = np.random.random(30)
print(Z)
m= Z.mean()
print(m)

[0.93900378 0.24783812 0.62207475 0.61966222 0.70242079 0.79681678
 0.15270592 0.23791809 0.95114716 0.68075468 0.46338491 0.34628832
 0.92982314 0.97830328 0.62118147 0.57076401 0.8269925  0.98508095
 0.56368717 0.54098403 0.14300365 0.04080357 0.63532882 0.42705211
 0.25251166 0.54592236 0.78556871 0.80359934 0.46222007 0.88462234]
0.5919154898206916


In [30]:
Z = np.ones((10,10))
Z[1:-1,:] = 5
print(Z)
            

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [32]:
0*np.nan

nan

In [34]:
np.nan == np.nan 

False

In [35]:
np.inf > np.nan

False

In [36]:
np.nan - np.nan 

nan

In [37]:
0.3 == 3*0.1

False

In [40]:
Z = np.diag(1+np.arange(4),k = -1)
print(Z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [42]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1 
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [46]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [51]:
Z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [55]:
Z = np.random.random((5,5))
print(Z)
Zmax,Zmin = Z.max(),Z.min()
Z = (Z - Zmin) / (Zmax-Zmin)
print("normalize olmuş tablo")
print(Z)

[[0.92846754 0.57067836 0.26496754 0.50784387 0.27922245]
 [0.46968549 0.54893089 0.88330632 0.54030688 0.02316539]
 [0.80794049 0.62963717 0.62695637 0.34054026 0.0691483 ]
 [0.99194218 0.75924907 0.70449686 0.32659887 0.59559868]
 [0.08935736 0.70753052 0.23545557 0.34947078 0.81509028]]
normalize olmuş tablo
[[0.9344796  0.56515905 0.24959531 0.50029943 0.26430966]
 [0.46091123 0.54271067 0.88786286 0.53380871 0.        ]
 [0.81006803 0.62601807 0.62325088 0.32760371 0.04746492]
 [1.         0.7598073  0.70329046 0.31321299 0.59088254]
 [0.06832531 0.70642189 0.21913219 0.33682206 0.81744825]]


In [60]:
color = np.dtype([("r",np.ubyte,1),
                ("g",np.ubyte,1),
                ("b",np.ubyte,1),
                ("a",np.ubyte,1)])


In [65]:
Z = np.dot(np.ones((5,3)),np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [71]:
Z = np.arange(11)
Z[(3 < Z)& (Z<=8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [75]:
print(sum(range(5),-1))
from numpy import* 
print(sum(range(5),-1))

10
10


In [78]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.trunc(Z + np.copysign(0.5,Z))) #searxh later 

[ 4.53185672 -1.37734813 -5.74716207 -9.0068977   8.05727002  8.37500961
 -6.18671021  6.18147641 -2.14408736  7.71975194]
[ 5. -1. -6. -9.  8.  8. -6.  6. -2.  8.]


In [88]:
Z = np.random.uniform(0,10,10)
print(Z)
print(Z - Z%1) #çok iyi ya ondalıklı olanların tam kısmını veriyor. 

print(np.floor(Z))

print(np.ceil(Z)-1)

print(np.trunc(Z))

[2.93817288 2.40641025 0.152694   4.92084067 4.4135199  9.09285568
 0.22179829 4.19391782 9.38912092 4.24010971]
[2. 2. 0. 4. 4. 9. 0. 4. 9. 4.]
[2. 2. 0. 4. 4. 9. 0. 4. 9. 4.]
[2. 2. 0. 4. 4. 9. 0. 4. 9. 4.]
[2. 2. 0. 4. 4. 9. 0. 4. 9. 4.]


In [90]:
Z= np.zeros((5,5))
Z +=np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [94]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=integer,count=-1)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [95]:
z = np.random.random(10)
z.sort()
print(z)

[0.06072659 0.36170634 0.37973588 0.41294842 0.44131862 0.54341392
 0.67608022 0.81372658 0.88332907 0.89444464]


In [99]:
Z = np.arange(10)
np.add.reduce(Z)


45